version: "3.9"
   
services:
  nginx:
    build: . 
    links:
      - vault
    ports:
      - "8080:80"
  vault:
    image: hashicorp/vault:1.7.0
    image: vault
    command:
      [ vault, server,  -dev, -dev-root-token-id, root , -dev-listen-address=0.0.0.0:8200]
    ports: 
      - 8200:8200
