version: "3.9"
   
services:

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
        - 8080:80
    volumes:
      - ./nginx/html:/usr/share/nginx/html
      - ./nginx/conf/nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - vault-01
      - vault-02
  vault-01:
    image: hashicorp/vault:1.7.3
    command:
      [ vault, server,  -dev, -dev-root-token-id, root , -dev-listen-address=0.0.0.0:8200]
  vault-02:
    image: hashicorp/vault:1.7.3
    command:
      [ vault, server,  -dev, -dev-root-token-id, root , -dev-listen-address=0.0.0.0:8200]
    